version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      "8080:8080"
    depends_on: 
      - reactionary_db
      - reactionary_broker
  reactionary_db:
    container_name: "reactionary-database"
    image: "postgres" # use latest official postgres version
    ports:
      - "5435:5435"
    env_file:
      - .env
    volumes:
      - reactionary-database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    command: -p 5435
  reactionary_broker:
    container_name: "reactionary-broker"
    image: "redis"
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - reactionary-broker-data:/var/lib/redis/data/
    command: redis-server
